spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.10:3306/gulimall_pms?useSSL=false
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  jackson:
    deserialization:
      #      不允许`float`强转成`int`
      ACCEPT_FLOAT_AS_INT: false
    date-format: yyyy-MM-dd HH-mm-ss
    time-zone: GMT+8
  thymeleaf:
    #关闭thymeleaf的缓存
    cache: true
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 192.168.56.10
    port: 6379
#    password: xxx

#    alicloud:
#      access-key: LTAl4FwfjSycd1APnuG9bjj
#      secret-key: O6xaxyiWfSlitcOkSuK27ju4hXT5HI
#      oss:
#        endpoint: oss-cn-beijing.aliyuncs.com
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #起别名
  type-aliases-package: com.atguigu.gulimall.product.entity
  global-config:
    db-config:
      id-type: auto    #主键自增
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

server:
  port: 10000
logging:
  level:
    com.atguigu.gulimall: error

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000




